%{
#include "hpp.hpp"
%}
%option noyywrap
%option yylineno
S [+-]?
N [0-9]+
%%
#[^\n]*\n		{}					/* # line comment with leading endline */
^\.end			{yyterminate();}	/* stop lexer */

{S}{N}\.{N}		TOC(Num,NUM)		/* floating point */
{S}{N}			TOC(Int,NUM)		/* integer */

[a-zA-Z0-9_]+	TOC(Sym,SYM)		/* symbol */

\(				TOC(Op,LP)			/* parens */
\)				TOC(Op,RP)
\[				TOC(Op,LQ)
\]				TOC(Op,RQ)
\{				TOC(Op,LC)
\}				TOC(Op,RC)

\=				TOC(Op,EQ)

%%
